### ISSUE TITLE
Re-styling chart on `roxie-theme-dark`

### ISSUE THREAD

**Issue by huytrongnguyen** [huytrongnguyen/roxie#15]
```scss
.c3 {
  path, .tick line { stroke: $border-color; }
  text, .c3-chart-arcs-title { fill: $body-color; }
  .c3-tooltip {
    background-color: $body-bg;
    tr { border: 1px solid $border-color; }
    th { background-color: $component-cap-bg; }
    td { background-color: $body-bg; border-left: 1px dotted $border-color; }
  }
}
```
