### ISSUE TITLE
Re-styling input group on `roxie-theme-dark`

### ISSUE THREAD

**Issue by huytrongnguyen** [huytrongnguyen/roxie#16]
```scss
.input-group-text {
  color: $body-color;
  background-color: $component-cap-bg;
  border: 1px solid $border-color;
}
```
