### ISSUE TITLE
Supports sidebar styling

### ISSUE THREAD

**Issue by huytrongnguyen** [huytrongnguyen/roxie#33]
```scss
.sidebar-nav {
  display: flex;
  flex-flow: column;
  overflow-y: auto;
  .nav-dropdown-items {
    flex-flow: column;
    .nav-link {
      padding-left: 2.5rem;
    }
  }
}

.nav-link {
  .nav-icon { width: 1.5rem; }
}

.roxie-theme-* {
  .nav-link {
    color: $body-color;
    &:hover, &:focus {
      color: $body-color;
      background-color: $component-hover-bg;
    }
    &.active {
      color: $component-active-color;
      background-color: $component-active-bg;
    }
    &.disabled { color: $component-disabled-color; }
  }
}
```
