### ISSUE TITLE
Grid enhancement

### ISSUE THREAD

**Issue by huytrongnguyen** [huytrongnguyen/roxie#40]
```tsx
import React, { useState, useEffect, HTMLAttributes, ReactElement, PropsWithChildren, Children } from 'react';
import { DataStore } from '@roxie/core';
import $ from 'jquery';
import { Ext } from '@thor/core';

interface GridColumnPropsType extends HTMLAttributes<HTMLDivElement> {
  headerName: string,
  field: string,
  cellRenderer?: (value: any, record: any, rowIndex: number, colIndex: number) => string | ReactElement,
}

export function GridColumn(props: GridColumnPropsType) {
  return null;
}

interface GridPropsType extends PropsWithChildren<any> {
  store: DataStore<any>,
  className?: string,
}

const SCROLL_WIDTH = Ext.getScrollWidth();

export function Grid(props: GridPropsType) {
  const [gridId] = useState(Ext.guid('grid-')),
        [columns, setColumns] = useState([] as GridColumnPropsType[]),
        [data, setData] = useState([]);

  useEffect(() => {
    const subscription = props.store.subscribe(value => setData(value || []));

    setColumns(Children.toArray(props.children).map(child => child.props));

    const header = $(`#${gridId} .rx-grid-header-viewport`),
          body = $(`#${gridId} .rx-grid-body-viewport`);
    $(`#${gridId} .rx-grid-body-viewport`).on('scroll', function () { header.scrollLeft(body.scrollLeft()) });
    return () => {
      subscription.unsubscribe();
      $(`#${gridId}`).off('scroll');
    }
  }, [])

  return <div id={gridId} className={`rx-grid d-flex flex-column fullscreen ${props.className || ''}`}>
    <div className="rx-grid-header-viewport d-flex no-scroll">
      <div className="rx-grid-header-container d-flex">
        <div className="rx-grid-header-row d-flex flex-row">
          {columns.map((col: GridColumnPropsType, index) => {
            const { headerName, field, className = '', cellRenderer, ...others } = col;
            return <div className={`rx-grid-header-cell d-flex p-2 ${className}`} {...others} key={index}>{headerName}</div>
          })}
          <div style={{width:SCROLL_WIDTH}} />
        </div>
      </div>
    </div>
    <div className="rx-grid-body-viewport d-flex fullscreen">
      <div>
        <div className="rx-grid-body-container d-flex">
          <div className="rx-grid-body d-flex flex-column">
            {data.map((item, rowIndex) => {
              return <div className="rx-grid-row d-flex flex-row" key={rowIndex}>
                {columns.map((col, colIndex) => {
                  const { headerName, field, className = '', cellRenderer, ...others } = col;
                  return <div className={`rx-grid-cell d-flex p-2 text-break ${className}`} {...others} key={colIndex}>
                    {cellRenderer ? cellRenderer(item[field], item, rowIndex, colIndex) : item[field]}
                  </div>
                })}
              </div>
            })}
          </div>
        </div>
      </div>
    </div>
  </div>
}
```

```scss
.rx-grid {
  .rx-grid-header-container {
    .rx-grid-header-row {
      background-color: #f5f7f7;
      border-bottom: 1px solid #bdc3c7;
      .rx-grid-header-cell {
        border-right: 1px solid #bdc3c7;
        &:last-child {
          border-right: none;
        }
      }
    }
  }
  .rx-grid-body-viewport {
    font-size: 0.75rem;
    font-weight: 200;
    overflow-x: auto;
    overflow-y: scroll;
    .rx-grid-body-container {
      .rx-grid-row {
        border-bottom: 1px solid #d9dcde;
        .rx-grid-cell {
          border-right: 1px solid #d9dcde;
          &:last-child {
            border-right: none;
          }
        }
        &:last-child {
          border-bottom: none;
        }
      }
    }
  }
}
```
